### ISSUE TITLE
vercel 部署报错🐞 错误报告 

### ISSUE THREAD

**Issue by jacklu2016** [JimmyLv/BibiGPT#106]
## 错误描述 🤔
部署到vercel时，在build阶段报错
caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)

**Comment by liaosunny123** [comment]
同样遇到了这个情况：
```
error: API request failed
caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)
```

**Comment by zl0662** [comment]
是的，我也是这个问题

**Comment by zeylei** [comment]
这个问题我也遇到了 env我都配置了 一样有问题🤨

**Comment by UNICKCHENG** [comment]
导入 .env 后，重新 build，试一试？ @zeylei  @zl0662 @fangyuan99 @liaosunny123 @jacklu2016 
![image](https://github.com/JimmyLv/BibiGPT/assets/32270702/afbdd7d0-c082-4c7a-927f-471e405bf0b2)

**Comment by MinxZ** [comment]
<img width="316" alt="image" src="https://github.com/JimmyLv/BibiGPT/assets/20724988/5ad4de2c-2ba7-4453-b279-08dbd2bf9986">
这几个文件里面的DSN和org project改成自己sentry里面的

**Comment by hansipingping** [comment]
> 这个问题我也遇到了 env我都配置了 一样有问题🤨

vercel部署的时候不会读取.env文件，需要在vercel的environment variables里面设置

**Comment by JimmyLv** [comment]
https://vercel.com/docs/concepts/projects/environment-variables
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables
