### ISSUE TITLE
B站的有些视频为什么获取不到字幕

### ISSUE THREAD

**Issue by yolandafans** [JimmyLv/BibiGPT#113]
# 功能改善建议 🚀

欢迎在此分享您对功能的改善建议，我们期待听到您的想法和建议。

## 您的建议是什么？ 🤔

请简要描述您的功能改善建议，包括您的目标和想法。

如果您的建议是解决某个特定问题的，请尽可能提供更多的上下文和细节。

视频地址：https://www.bilibili.com/video/BV1CT411p7Cy/

感谢您的分享和支持！🙏

**Comment by JimmyLv** [comment]
现在可以成功转录了哦😁
<img width="1223" alt="Google Chrome-BibiGPT · AI 音视频内容一键总结-007156-20230512" src="https://github.com/JimmyLv/BibiGPT/assets/4997466/0d39e273-e8e4-4fa2-9fb7-00019c1c81ae">
