### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by MotWnb** [JimmyLv/BibiGPT#119]
## Error uploading fileToUpload: new row violates row-level security policy for table "objects" Made with by JimmyLv on GitHub

**Comment by JimmyLv** [comment]
非常高兴地通知您，之前困扰了 1 个多月的 Bug 终于修复了！

#BibiGPT 现在可以正常上传本地文件啦，之前新注册的用户有概率会遇到的问题，现在终于不会再发生了，感谢您的耐心等待！

再次感谢早期的支持和理解！
![RvJNb1fpUo9PcxxsY9xckW2Cn2g](https://github.com/JimmyLv/BibiGPT/assets/4997466/bdc17931-eaab-4811-bf08-ac3cf8e0babb)
