### ISSUE TITLE
🐞 错误报告 是否无法用api-key

### ISSUE THREAD

**Issue by fangyuan99** [JimmyLv/BibiGPT#123]
# 错误报告 🐞

现在是否不支持填写自己的key，我填了一个确定可用的`openai-key`，但是点击激活的时候显示`402 License Key 不合法`

**Comment by Supertramp7224** [comment]
我的也是

**Comment by JimmyLv** [comment]
Hello，现在大家可以试试自己的apikey方式哦，现在我重新兼容支持了下 😁
（1. 为了防止被滥用，暂时限制为每日30次哦）
（2. 考虑到服务器资源有限，若需要更多次数可以加我）

![](https://b.jimmylv.cn/wechat.jpg)
