### ISSUE TITLE
🚀 功能改善：输出字幕和正文的中英文对照

### ISSUE THREAD

**Issue by webnet918** [JimmyLv/BibiGPT#125]
# 功能改善建议 🚀
软件非常棒，给喜欢学习的人提供了很大帮助，希望在现有基础上增加自动断句功能

## 您的建议是什么？ 🤔

通过油管的一段视频进行了测试，生成的结果没有标点符号，大量口语中的过渡词也导致整个句子的可阅读性不太好。如果在断句，并使整句话处在同一个时间轴下的话，体验应该会有质的变化。

输出的字幕和正文如果能有中英文对照就太好了，下面是我测试的视频源供参考
https://www.youtube.com/watch?v=kt6V4ai60fI&list=PLVgHx4Z63paYiFGQ56PjTF1PGePL3r69s

感谢您的分享和支持！🙏

**Comment by JimmyLv** [comment]
昨天刚做了YouTube的字幕多语言翻译啦！
![【BibiGPT】每日常规更新：字幕翻译 搜索 跳转-封面](https://github.com/JimmyLv/BibiGPT/assets/4997466/68e0fed4-2890-4bb1-a41f-6127dc27a1c5)


https://www.bilibili.com/video/BV1Mx4y1Z7XG/
