### ISSUE TITLE
请问下BILIBILI_SESSION_TOKEN怎么获取

### ISSUE THREAD

**Issue by MaxwellEdisons** [JimmyLv/BibiGPT#146]
请问下BILIBILI_SESSION_TOKEN怎么获取

**Comment by 0n1onr1ng** [comment]
获取Bilibili Session Token：
1. 打开B站网站并登录账号.
2. 按下F12打开开发者工具。
3. 点击Application选项卡，然后选择左侧的Cookies。
4. 在Cookies中找到SESSDATA，复制其值即为BilibiliSession Token.
请注意，Bilibili Session Token具有一定的有效期，如果过期需要重新获取
