### ISSUE TITLE
🔧 项目维护 下载了代码运行，启动后的版本跟b.jimmylv.cn有很大的不同，是开源版本就是这样吗？

### ISSUE THREAD

**Issue by MaxwellEdisons** [JimmyLv/BibiGPT#152]
# 项目维护问题和建议 🔧

 请问下，下载了代码运行，启动后的版本跟b.jimmylv.cn页面有很大的不同，包括思维导图、字幕下载、文本汇总等功能都没有，是因为开源版本就是这样吗？
谢谢

**Comment by JimmyLv** [comment]
是的哈
