### ISSUE TITLE
🚀 功能改善 `SAVESUBS_X_AUTH_TOKEN=` 如何获取？

### ISSUE THREAD

**Issue by Gy-Hu-Star** [JimmyLv/BibiGPT#156]
你好， `SAVESUBS_X_AUTH_TOKEN` 请问如何获取？在savesubs设置里还是GET请求里面都没找到

**Comment by JimmyLv** [comment]
在request header里面呢

**Comment by Rajashekarksreddy** [comment]
i did'nt get exactly? what can i type request header exactly
