### ISSUE TITLE
🐞 错误报告 fetch failed

### ISSUE THREAD

**Issue by freesnowmountain** [JimmyLv/BibiGPT#157]
# 错误报告 🐞

fetch failed

## 错误描述 🤔
环境都配置好了，本地运行之后可以正常打开localhost:3000。一键总结之后网页报错如下图。
![QQ截图20230807172428](https://github.com/JimmyLv/BibiGPT/assets/102673901/06da91f3-c491-43f1-ab20-37258d7fa032)

观察编译器，可以顺利完成读取翻译功能，似乎是在读取openai的api时报错的。api没有问题，刚刚创建的，并且在其他地方可以正常调用。
![image](https://github.com/JimmyLv/BibiGPT/assets/102673901/377b3af7-bb10-4290-b6e8-3ec1b10877a0)

查看了其它GitHub Issue，好像没用这种用到一半报错的。

#终端输出
![image](https://github.com/JimmyLv/BibiGPT/assets/102673901/39ced620-569c-411d-b7db-bfd3f88cf27d)

**Comment by JimmyLv** [comment]
在本地应该需要配置代理的，![image](https://github.com/JimmyLv/BibiGPT/assets/4997466/51227953-4c54-46a1-9f19-7f6901863a13)
