### ISSUE TITLE
文字内容做成视频的意义🤔

### ISSUE THREAD

**Issue by MysteryMulberry** [JimmyLv/BibiGPT#19]
科技博主把三百字的知识点写成五千字的文稿剧本，做成18分钟的视频。网网友用Ai把这18分钟视频浓缩成300字的知识点。

这就是Web3.1吗？

**Comment by goxofy** [comment]
300字就能理解

**Comment by NNGTHB** [comment]
或许你知道输入和输出的区别吗？

**Comment by JHanLu** [comment]
not everything has a 意义

**Comment by cqh6666** [comment]
不是所有人都一定要去接收这18分钟的视频内容啊

**Comment by JimmyLv** [comment]
讨论可以移步 #公众号：魔法司

[mofa.si](https://mofa.si) 内容社群正在建设中

**Comment by JimmyLv** [comment]
哈哈哈，技术小伙伴，来 Discussion 讨论吧： https://github.com/JimmyLv/BibiGPT/discussions
