### ISSUE TITLE
less is more！

### ISSUE THREAD

**Issue by Evani300** [JimmyLv/BibiGPT#2]
立青！我太喜欢你关于gpt的改造了或许你只是基于字幕进行的缩略处理但是，如果真的能做到视频模态到文字模态的信息精简这会创造很大的价值，在大数据时代数据对于我们而言less is more。我希望你可以和我取得联系！
我目前在一家早期投资基金我们的模式是通过标准化投资+加速的形式帮助创业团队成长。从2019年创立至今，我们已经投资了200多家早期创业团队，并手把手帮助他们做商业化的落地和加速。（微信：c13559870609)

**Comment by JimmyLv** [comment]
😉
