### ISSUE TITLE
支持输出的语言

### ISSUE THREAD

**Issue by SUDre** [JimmyLv/BibiGPT#23]
油管上一些中文内容，有时候会总结成英文；vice versa
希望能够自己选择输出的语言

**Comment by JimmyLv** [comment]
nice，感谢反馈！看来是我的prompt没生效🤣

**Comment by JimmyLv** [comment]
已经支持啦~ 感谢建议！

<img width="1107" alt="Google Chrome-httpsb jimmylv cn-006445-20230315" src="https://user-images.githubusercontent.com/4997466/225185667-9cccaa03-8707-495b-960b-af3dc022c5f5.png">
