### ISSUE TITLE
总结时报错

### ISSUE THREAD

**Issue by RyuraeleN** [JimmyLv/BibiGPT#28]
服务器上部署完项目之后点击“一键总结”出现如下报错
error - node_modules/@upstash/redis/esm/platforms/nodejs.js (22:0) @ <unknown>
error - Cannot read properties of undefined (reading 'startsWith')
null
请问这个是哪个地方 出问题了呢？
另外提个小小的建议，我觉得总结输出的内容可以适当分为“精简”“适中”和“详细”三个档位会不会更好呢？大概也能更适宜不同人的不同需求吧。

**Comment by JimmyLv** [comment]
感谢建议！

<img width="1107" alt="Google Chrome-httpsb jimmylv cn-006445-20230315" src="https://user-images.githubusercontent.com/4997466/225185432-a4582210-42ad-435d-9daa-a757cc01ccf6.png">

**Comment by zyjjoe006** [comment]
遇到了同样的问题，请问要如何修改

**Comment by zyjjoe006** [comment]
> 请问是报了什么错误呢？

error - node_modules/@upstash/redis/esm/platforms/nodejs.js (22:0) @ <unknown>
error - Cannot read properties of undefined (reading 'startsWith')
