### ISSUE TITLE
[功能请求]更多参数自定义

### ISSUE THREAD

**Issue by NNGTHB** [JimmyLv/BibiGPT#31]
![image](https://user-images.githubusercontent.com/115760745/224464910-1ce3542f-a8de-4675-a112-2c67eaceaab1.png)
请问能增加支持调节参数的选项吗？类似上图这种

**Comment by JimmyLv** [comment]
Thanks for the suggestion, it's online!

<img width="1107" alt="Google Chrome-httpsb jimmylv cn-006445-20230315" src="https://user-images.githubusercontent.com/4997466/225185386-bcb84476-d192-4a22-bab0-63fa86498b78.png">
