### ISSUE TITLE
output behavior: 建议：希望作者把选中自动复制的这个功能给关了

### ISSUE THREAD

**Issue by maye174** [JimmyLv/BibiGPT#43]
本人有思考习惯，习惯于选中后阅读，所以选中后自动复制虽然不影响什么，但是对我的剪贴板保存的记录是个挑战。既然有一键复制的按钮，我认为选中自动复制这个功能可以关闭，也能给用户多一点选择

**Comment by JimmyLv** [comment]
嗯嗯，感谢建议～！

**Comment by maidangzhu** [comment]
我用的paste剪贴管理软件，会自动去重哈哈

**Comment by JimmyLv** [comment]
哈哈哈，确实是个好建议，我已经关掉啦～
