### ISSUE TITLE
prompt process: 选择中文或日文，时常它还是返回英文结果

### ISSUE THREAD

**Issue by Yuiffy** [JimmyLv/BibiGPT#46]

**Comment by Ingnaryk** [comment]
我也遇到了这种情况。环境是分段总结。我猜测总结的开头如果是专业名词（如英文缩写等），那么本段总结就会全英文。

**Comment by JimmyLv** [comment]
有可能是的，哈哈哈哈 我想一想怎么规避掉

**Comment by JimmyLv** [comment]
我最近做了一个小改进，是否效果会更好呢？

观察中...

**Comment by laocan** [comment]
把提示词，直接用中文字符串试试

**Comment by JimmyLv** [comment]
嗯嗯，感谢建议 @laocan 我刚好也加上了，😁 
真的是很棒的技巧 https://platform.openai.com/docs/guides/speech-to-text/prompting
