### ISSUE TITLE
process input: 长视频只能总结一部分

### ISSUE THREAD

**Issue by SlatitudeChou** [JimmyLv/BibiGPT#47]

**Comment by wangwei8828** [comment]
对呀，还是受chatGPT断句的影响。

**Comment by SlatitudeChou** [comment]
加一个自动分段的脚本进去怎么样

**Comment by JimmyLv** [comment]
欢迎PR！ 哈哈哈 我觉得可以加一个继续总结的按钮就行了，接下来就会做的

**Comment by Cyiming** [comment]
应该是因为单次输入有上限

**Comment by fulequn** [comment]
> 
之前看到https://zhuanlan.zhihu.com/p/610250035这里面引用了这个项目。不知道可不可以借鉴那个分段的地方，就在“预处理字幕文本”这步。

**Comment by JimmyLv** [comment]
> https://zhuanlan.zhihu.com/p/610250035

404 了 🫠
你似乎来到了没有知识存在的荒原


不过我昨天也做了处理，大家再试试看呢？传视频的效果应该好很多了。
