### ISSUE TITLE
希望能推出 Tampermonkey 插件

### ISSUE THREAD

**Issue by HChenZi** [JimmyLv/BibiGPT#5]
感觉会比改 url 用起来更方便些
<s>试着自己整了一个，但有遇到跨域问题<s/>

**Comment by JimmyLv** [comment]
嗯嗯，感谢建议！（和尝试😁）

**Comment by mmqmzk** [comment]
```javascript
javascript:(function(){location.href=location.href.replace('bilibili.com','bilibili.jimmylv.cn')}())
```

试试用 bookmarklet，随便保存个书签，右键修改，把地址换成上面的代码，在视频页面点击该书签

**Comment by JimmyLv** [comment]
天呐，太棒了🤣

也没有那种，一键在页面上点击“按钮”，然后添加这段代码到书签栏的效果？

**Comment by JimmyLv** [comment]
调研了，看来加一个 a 标签即可：[What are Bookmarklets? How to Use JavaScript to Make a Bookmarklet in Chromium and Firefox](https://www.freecodecamp.org/news/what-are-bookmarklets/)

**Comment by JimmyLv** [comment]
_Opera, Google Chrome and Safari do not provide a way to add new elements to the Favorites (Bookmarks) from JavaScript._

_There was an API for that however, which is the_ [_Window.external_](https://developer.mozilla.org/en-US/docs/Web/API/Window/external) _API, and I believe it used to work as_ `_window.external.AddFavorite()_` _in Internet Explorer, and_ `_window.sidebar.addPanel()_` _in Firefox (obsolete, deprecated, i.e. dead,_ [_see_](https://developer.mozilla.org/en-US/docs/Web/API/Window/sidebar) _for the API)._

**Comment by saccohuo** [comment]
+1

**Comment by JimmyLv** [comment]
有朋友做了也，太感谢啦！ [快捷跳转BiliGPT - Source code](https://greasyfork.org/en/scripts/461214-%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%ACbiligpt/code)
