### ISSUE TITLE
有些时候导出到飞书的内容前面会有一行空白，强迫症用户看着稍微有点难受

### ISSUE THREAD

**Issue by excelsior222** [JimmyLv/BibiGPT#54]
同时导出到flomo的就没有这个问题，不知道是什么原因导致的

![image](https://user-images.githubusercontent.com/93578207/226097142-fbca80ef-92bc-4cbf-88bd-6dc3108f5708.png)

**Comment by conglinyizhi** [comment]
抱歉给您的体验带来了不便，这部分代码是我完成的，开发的时候比较仓促，稍后我会提交新的代码合并请求

**Comment by excelsior222** [comment]
> 抱歉给您的体验带来了不便，这部分代码是我完成的，开发的时候比较仓促，稍后我会提交新的代码合并请求

您好，不知道这个问题是否已经修复过，我今天在尝试向飞书推送的时候，似乎还有同样的问题，辛苦再排查一下呢，感谢~

![image](https://user-images.githubusercontent.com/93578207/226525764-dab1252b-271f-4901-a39f-51aba681145e.png)

**Comment by conglinyizhi** [comment]
> > 抱歉给您的体验带来了不便，这部分代码是我完成的，开发的时候比较仓促，稍后我会提交新的代码合并请求
> 
> 您好，不知道这个问题是否已经修复过，我今天在尝试向飞书推送的时候，似乎还有同样的问题，辛苦再排查一下呢，感谢~
> 
> ![image](https://user-images.githubusercontent.com/93578207/226525764-dab1252b-271f-4901-a39f-51aba681145e.png)
> 
> 
> 

已经尝试过了，我尝试将每个推送消息的第一个字符删除，但是他并不奏效，我认为可能是更深层次的原因，因为我也需要这个功能，所以我会尽快排查原因

**Comment by JimmyLv** [comment]
先前没发布，再试试看呢？
