### ISSUE TITLE
时间戳的生成好像有点BUG

### ISSUE THREAD

**Issue by excelsior222** [JimmyLv/BibiGPT#55]
生成了两个视频，都只显示到前5秒

![image](https://user-images.githubusercontent.com/93578207/226096555-4754d166-7f9d-4908-9cf9-d2ff010a6de7.png)

![image](https://user-images.githubusercontent.com/93578207/226096563-7e758bf0-24d5-4b41-8798-66c01dcea90a.png)

**Comment by JimmyLv** [comment]
已记录，后续排查一下 BV1mx4y1F7ok

**Comment by JimmyLv** [comment]
已经处理啦，可以再试试看哟。

**Comment by excelsior222** [comment]
> 已经处理啦，可以再试试看哟。

BV1mx4y1F7ok这个视频，刚刚试了一下，已经解决啦~

不过尝试转另一个新视频的时候又出现了这个问题lol（请叫我捉虫小能手

我有观察到新的这个问题视频解析出来是无字幕，不知道是否和这个有关

![image](https://user-images.githubusercontent.com/93578207/226525404-fdf977d9-2ec8-4330-91d5-2f1e4b6542a5.png)

https://bilibili.com/video/BV1fA411y7Dm

**Comment by JimmyLv** [comment]
哈哈哈哈 捉虫小能手！确实没有字幕的视频，GPT会自己瞎编时间戳，😂 后面我会做识别音频的
