### ISSUE TITLE
视频出现文字太多错误，怎么调节参数都不能成功。

### ISSUE THREAD

**Issue by fulequn** [JimmyLv/BibiGPT#58]
OpenAl API Error [Bad Request]:This model'smaximum context length is 4097 tokens.
However,you requested 4285 tokens (3575 inthe messages,710 in the completion).Pleasereduce the length of the messages orcompletion.

**Comment by JimmyLv** [comment]
感谢反馈！！试试把详细程度调到最低呢？🫡 我明天会再看看，具体的视频链接你发我一个哦（方便的话

**Comment by fulequn** [comment]
`[](url)`

> 感谢反馈！！试试把详细程度调到最低呢？🫡 我明天会再看看，具体的视频链接你发我一个哦（方便的话

谢谢你的回复，我原本试过直接降详细程度。发现降了那个报错的数字也一样，我就把emoji去掉了，之后大纲层级和要点数目都降低后就可以了。不知道其他长视频也是不是这样。

**Comment by JimmyLv** [comment]
哈哈哈，感谢捉虫！🫣 难道是因为emoji占的字符比较多？
