### ISSUE TITLE
填了openai的api key后点击总结会跳转到shop

### ISSUE THREAD

**Issue by kong-eng** [JimmyLv/BibiGPT#59]
# 错误报告 🐞

填了openai的api key后点击总结会跳转到shop

## 错误描述 🤔

填写了我的api key后，输入B站链接，然后会提示**未知错误**而不是生成总结内容

## 附加信息 📝

![图片](https://user-images.githubusercontent.com/64780855/226239153-db486d74-262a-4a2e-a0b4-b4fdb2be8698.png)

感谢您的反馈！🙏

**Comment by JimmyLv** [comment]
感谢反馈，让我来测试一下！
我好久没有试过用自己的apikey了，这条链路可能会有点问题。🫠

**Comment by Cyiming** [comment]
最新版本的锅

**Comment by JimmyLv** [comment]
先前的问题，已经修正了 🥲
