### ISSUE TITLE
请问INTERNAL_API_HOSTNAME配置自己应该怎样获取？

### ISSUE THREAD

**Issue by fulequn** [JimmyLv/BibiGPT#60]
在复现这个程序的时候，一键部署出现了下列问题：

`
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\workspace\Python\BibiGPT-main\.env
warn  - Your project has `@next/font` installed as a dependency, please use the built-in `next/font` instead. The `@next/font` package will be removed in Next.js 14. You can migrate by running `npx @next/codemod@latest built-in-next-font .`. Read more: https://nextjs.org/docs/messages/built-in-next-font
`destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/:path*","destination":"api.example.com/api/:path*"}
`

我查看后应该是设置里的这个需要更改，请问INTERNAL_API_HOSTNAME=api.example.com是怎样获取的

**Comment by JimmyLv** [comment]
这是我自己的服务呐，也可以不填的，你拉一下最新代码 🤣
