### ISSUE TITLE
没有字幕的视频也会生成笔记

### ISSUE THREAD

**Issue by Cyiming** [JimmyLv/BibiGPT#66]
# 会根据视频标题和简介生成

比如av213920557 
![image](https://user-images.githubusercontent.com/45073586/227393444-417ff8d7-a9df-4882-aa5a-770e19919d20.png)

# 有时候简介内容少还会胡说八道

比如BV13k4y1b7cZ 会说什么腾讯股价历史新高了

# 建议如果没有字幕不默认生成笔记

**Comment by JimmyLv** [comment]
嗯，确实是。但源头是下一步我得做语音识别文本🤣
现在只根据标题&简介内容，GPT会自由发挥，=。=

**Comment by JimmyLv** [comment]
谢谢反馈，最近已经加上提示啦~
![Google Chrome-httpsb jimmylv cnvideoBV1Sk4y1471G-001808-20230329](https://user-images.githubusercontent.com/4997466/228568280-8e7b9f7e-59ed-47c3-9488-0b87152b1f2c.png)
