### ISSUE TITLE
🐞 错误报告 EDGE_FUNCTION_INVOCATION_FAILED

### ISSUE THREAD

**Issue by justinzpc** [JimmyLv/BibiGPT#69]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/16377701/227563401-e9035577-7c3e-4212-86b1-781eeb211eb8.png">
## 附加信息 📝
i  deploy success, but click the button call this error,
does anybody know how to fix it?

感谢您的反馈！🙏

**Comment by conglinyizhi** [comment]
您好

关于您提及的问题，基于目前的信息，目前我无法判断具体是哪个部分出现了问题。

或许您的控制台给出了更多的错误提示信息，如果有，请发出来，这可以方便其他人帮助您定位错误。

**Comment by JimmyLv** [comment]
@justinzpc 你这个是自己部署的版本哇？

**Comment by justinzpc** [comment]
是的，我自己在vercel deploy了，但是调用api总结的时候报错，vercel 的log 也看不出什么问题来，头大了

**Comment by justinzpc** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/16377701/227706263-a1511f58-3021-4030-8250-dbc786cf8156.png">
这是vercel里面的log

**Comment by justinzpc** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16377701/227916054-7168da1c-4ee8-4887-9eba-45bdfc96c442.png">
为什么你这里的api 名称跟我clone 下来的不一样啊大佬

**Comment by JimmyLv** [comment]
是的啦，我在把 BibiGPT 功能迁移到 mofa.si 平台，这个平台不只有音视频的能力，哈哈哈哈 暂时还没有 ready，所以没有开源啦
