### ISSUE TITLE
B站视频使用AV号会获取不到字幕

### ISSUE THREAD

**Issue by WANGtheneighbor** [JimmyLv/BibiGPT#7]
我使用了脚本将BV号都替换成了AV号，就发现所有视频如果在网站上提交AV号就会提示无法获取字幕，切换成BV就好了

**Comment by JimmyLv** [comment]
嗯嗯，AV号现在确实不支持，因为获取字幕的API不一样🤣

你可以试试改代码用 cid

**Comment by JimmyLv** [comment]
现在支持av号啦，感谢建议
