### ISSUE TITLE
🐞 错误报告 

### ISSUE THREAD

**Issue by conglinyizhi** [JimmyLv/BibiGPT#70]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

图片中反应目前总结返回的信息出现了两个问题

- 格式错误
- 总结的视频内容错误（不是我需要的视频）

![图片](https://user-images.githubusercontent.com/42381347/227678303-28f7a48e-7963-44fc-b977-8239caaa2857.png)

### 操作方法

- 打开 B 站视频（https://bilibili.com/video/av389981107）
- 使用书签的方式打开网站
- 等待总结完成后点击继续总结
- 调整总结参数
- 点击开始总结

**Comment by JimmyLv** [comment]
感谢反馈！ 我在本地来试试看

**Comment by JimmyLv** [comment]
现在可以啦，可能是 av389981107 号的之前有问题

![Google Chrome-httpsb jimmylv cnvideoav389981107vd_sourcedd5a650b0ad84edd0d54bb18196ecb86-001802-20230329](https://user-images.githubusercontent.com/4997466/228565897-36154b1f-76b5-4441-9ba3-9938c4d89192.png)
