### ISSUE TITLE
🐞 错误报告 

### ISSUE THREAD

**Issue by xyjandyyk** [JimmyLv/BibiGPT#71]
我已经填入了自己的api，但是依旧会跳到付费界面

**Comment by xyjandyyk** [comment]
顺便一提我在本地和vercel都尝试过部署，但是本地的话会弹出'next' 不是内部或外部命令，也不是可运行的程序或批处理文件。在vercel中显示
error: API request failed
caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)

**Comment by Pengyoushiyige** [comment]
> 顺便一提我在本地和vercel都尝试过部署，但是本地的话会弹出'next' 不是内部或外部命令，也不是可运行的程序或批处理文件。在vercel中显示 error: API request failed caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)

The same problem here too...

**Comment by qq254348470** [comment]
> The same problem here too...

+1

**Comment by JimmyLv** [comment]
现在应该都可以啦，apikey的方式正常使用。
