### ISSUE TITLE
🚀 功能改善 在使用自己的apikey时希望能修改总结字数的上限

### ISSUE THREAD

**Issue by lyl199655** [JimmyLv/BibiGPT#72]
在使用自己的apikey时希望能修改总结字数的上限，稍微长一点的视频，总结的东西就会被截断，希望能自己设置字数限制。目前有的好像是单句的字数限制

**Comment by JimmyLv** [comment]
谢谢反馈，主要是单次的上限受API限制，用自己的apikey是一样的啦。

目前调节的单句字数长度，也会反应到返回的 max_tokens 上的：

```js
      max_tokens: Number(videoConfig.detailLevel) || (userKey ? 800 : 600),

```
