### ISSUE TITLE
user dashboard: 使用自己api的，无法加载缓存过的数据了

### ISSUE THREAD

**Issue by Duoduo23333333** [JimmyLv/BibiGPT#8]
使用自己api的，打开别的用户分析过的视频，依然要再分析一遍，并且自己分析过的也不能保存，刷新再提交一次就会再重新分析一次。

**Comment by JimmyLv** [comment]
账号系统在开发啦，🤣 

如果是用自己api key，我想的是简单搞个买断制就好了

当然也可以 clone 开源项目，自己搭服务器，这是关于成本的思考
