### ISSUE TITLE
🚀 功能改善 手机端访问时页面会不断放大缩小，影响使用

### ISSUE THREAD

**Issue by piratf** [JimmyLv/BibiGPT#81]
# 功能改善建议 🚀

欢迎在此分享您对功能的改善建议，我们期待听到您的想法和建议。

## 您的建议是什么？ 🤔

chrome 调试器选一个手机分辨率就可以复现，可能和首页标题文字不断变化有关。
希望可以更好地支持手机端访问。
![demo](https://user-images.githubusercontent.com/9389616/228837957-dfd11e7e-a876-4f87-b171-9393db1b1474.gif)

**Comment by JimmyLv** [comment]
就是呀，i18n没生效的时候就会这样 🤣

现在应该好啦～
