### ISSUE TITLE
📝 文档改善 

### ISSUE THREAD

**Issue by xingfanxia** [JimmyLv/BibiGPT#82]
# 文档改善建议 📝

欢迎在此分享您对文档的改善建议，我们期待听到您的想法和建议。

## 您的建议是什么？ 🤔

能解释一下要成功在Vercel部署运行起来需要配置哪些依赖吗? Vercel edge需要怎么配置

我现在配置了这些依赖还是不行
![Monosnap bibi-gpt – Environment Variables - Vercel 2023-03-30 20-39-51](https://user-images.githubusercontent.com/8936233/229016948-9854b479-a958-4369-bdd8-8ad582b88478.jpg)

![Monosnap Dashboard – Vercel 2023-03-30 20-40-15](https://user-images.githubusercontent.com/8936233/229017019-ffc89c4d-f9d5-48ff-9953-90ef07455de1.jpg)

![Monosnap Dashboard – Vercel 2023-03-30 20-40-39](https://user-images.githubusercontent.com/8936233/229017042-910a92c1-c58f-44e9-96ce-aff7f2eb30bc.jpg)

## 您的建议有哪些优势？ 🌟

目前没有关于vercel部署的文档

**Comment by justinzpc** [comment]
i'm stuck here too

**Comment by justinzpc** [comment]
这不是变量的问题，deploy是成功的，但是在调用api的时候报的这个invocation failed, 看vercel里面的log 也看不出什么问题

**Comment by justinzpc** [comment]
是不是变量里面的那个 INTERNAL_API_HOSTNAME 是必须的？一定要设置一个域名转发？

**Comment by JimmyLv** [comment]
我改天去掉相关代码吧，目前有一些冗余的内容
