### ISSUE TITLE
🐞 错误报告 

### ISSUE THREAD

**Issue by WanZunGe** [JimmyLv/BibiGPT#83]
# 错误报告 🐞

D:\Microsoft VS Code\my project\BibiGPT>npm run dev

> bibi-gpt@2.4.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error

求解，错误的原因

**Comment by JimmyLv** [comment]
No valuable information

**Comment by WanZunGe** [comment]
> No valuable information

没有对文件做任何修改，只在.example.env文件里添加了APIkey,然后直接在项目目录cmd，然后运行了npm run dev，然后就提示加载next.config.js失败了，是我的问题吗
