### ISSUE TITLE
🐞 错误报告 使用Vercel构建时sentry报错

### ISSUE THREAD

**Issue by xxtg666** [JimmyLv/BibiGPT#84]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

使用Vercel构建时报错：`sentry reported an error: Authentication credentials were not provided. (http status: 401)`

## 附加信息 📝

```
Failed to compile.
--
22:43:57.962 |  
22:43:57.962 | Sentry CLI Plugin: Command failed: /vercel/path0/node_modules/@sentry/cli/sentry-cli releases new c48f85a496f7c5d73324dfc439b36e1c040a8885
22:43:57.963 | error: API request failed
22:43:57.963 | caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)
22:43:57.963 |  
22:43:57.963 | Add --log-level=[info\|debug] or export SENTRY_LOG_LEVEL=[info\|debug] to see more output.
22:43:57.963 | Please attach the full debug log to all bug reports.
22:43:57.963 |  
22:43:57.963 | Sentry CLI Plugin: Command failed: /vercel/path0/node_modules/@sentry/cli/sentry-cli releases new c48f85a496f7c5d73324dfc439b36e1c040a8885
22:43:57.963 | error: API request failed
22:43:57.963 | caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)
22:43:57.963 |  
22:43:57.963 | Add --log-level=[info\|debug] or export SENTRY_LOG_LEVEL=[info\|debug] to see more output.
22:43:57.963 | Please attach the full debug log to all bug reports.
22:43:57.963 |  
22:43:57.963 |  
22:43:57.963 | > Build failed because of webpack errors
22:43:58.016 | Error: Command "npm run build" exited with 1
22:43:58.408 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

**Comment by NNGTHB** [comment]
同，现在无法使用vercel构建，网站也要付费了，导致完全用不了了

**Comment by bbingz** [comment]
哎，作者要变现了，有能力的就支持一下吧。

**Comment by JimmyLv** [comment]
请创建自己的 .env 文件或配置环境变量呀，https://nextjs.org/docs/basic-features/environment-variables

https://github.com/JimmyLv/BibiGPT/blob/main/.example.env

**Comment by JimmyLv** [comment]
> 哎，作者要变现了，有能力的就支持一下吧。

最近OpenAI封了我很多账号，无力承担每天的免费额度了
如果有需要，可以付费支持一下啦

另外，我发现... 就大家提的问题 🤣 
是不是我开一个「AI应用开发」的课程，更容易变现哦？ （认真脸

**Comment by xxtg666** [comment]
其实可以减少免费额度，或者要求用户填入自己的openai api key
或者也可以卖账号？不过这个风险比较大

**Comment by JimmyLv** [comment]
嗯呢，我正在修改成更合理的按时长收费，之前按次数，2小时和10分钟的视频都算一次。🤣
比如说，注册就获赠60分钟，邀请送时长之类，有点儿忙不过来了。前路漫漫啊

**Comment by bbingz** [comment]
其实按时长也并不准确，因为不是把对应时长的语音转文字，再小结的。而是直接取字幕来处理，应该按字幕文字数计算比较好。

**Comment by JimmyLv** [comment]
嗯嗯，语速不同，字数可能也不同。
对了我刚做了语音转文字啦，Whisper 的效果真的准得离谱，但主要就是贵 🤣 （后面会逐一迁移到这种模式，按照时长计费）

![Google Chrome-localhost3000langzh-001862-20230407](https://user-images.githubusercontent.com/4997466/230571021-81720100-e79e-4811-aae8-66f65a668d12.png)
![Uploading Google Chrome-localhost3000#access_tokeneyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjgxNDMzNzMxLCJzdWIiOiIzMGExNTc4Ni00NGIzLTRiYmQtODU2My03NjI4ZTVlODc2NzkiLCJlbWFpbCI6Imx2NDYwMDUxNTE4QGdtYWlsLmNvbSIsInBob25.png…]()

**Comment by Respawn-ID** [comment]
> 请创建自己的 .env 文件或配置环境变量呀，https://nextjs.org/docs/basic-features/environment-variables
> 
> https://github.com/JimmyLv/BibiGPT/blob/main/.example.env


配置了apikey的环境变量好想也没有用，需要配置别的？

**Comment by JimmyLv** [comment]
是的呀，每个都需要配置🥲 这是一个实战项目，这些配置都是一些SaaS标配的工具啦
