### ISSUE TITLE
🐞 错误报告 激活 License Key 失败

### ISSUE THREAD

**Issue by excelsior222** [JimmyLv/BibiGPT#91]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

3月18日购买了350次的License Key，今天在手机Web端登录激活时，首先是显示了500报错，后面再点了激活是402报错，刷新页面后剩余时长还是0分钟。

## 附加信息 📝

![image](https://user-images.githubusercontent.com/93578207/230698229-a577f78d-f3b6-47ec-a6d7-1208e66628a4.jpeg)

**Comment by JimmyLv** [comment]
非常感谢反馈，可以给我邮箱发一下license key吗？ 感谢～jimmy.jinglv@gmail.com

**Comment by excelsior222** [comment]
> 非常感谢反馈，可以给我邮箱发一下license key吗？ 感谢～[jimmy.jinglv@gmail.com](mailto:jimmy.jinglv@gmail.com)

不好意思回复晚啦，已经将Key发送到上述邮箱~

**Comment by JimmyLv** [comment]
非常感谢理解和支持，这个issue我就先关掉啦
