### ISSUE TITLE
🐞 错误报告 在vercel上部署构建的时候报错了

### ISSUE THREAD

**Issue by chaosgpt** [JimmyLv/BibiGPT#92]
# 错误报告 🐞
尝试在vercel部署该项目的时候，在构建阶段报如下错误，无法继续进行。

## 错误描述 🤔

Sentry CLI Plugin: Command failed: /vercel/path0/node_modules/@sentry/cli/sentry-cli releases new d6d7a13a7d3e05e5db5e95fa6275bfe5e907cffa
--
14:42:08.079 | error: API request failed
14:42:08.079 | caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)

**Comment by bbingz** [comment]
没有用的，放弃吧，我昨天也是装完依赖，解决完好几个报错，还剩一个 fs 解决不了。
建议使用chatGPTBox [https://github.com/josStorer/chatGPTBox]一个插件就解决问题了

**Comment by Jackiexiao** [comment]
你需要配置 .env 设置环境变量（这个仓库用到很多第三方的服务，sentry supabase 之类），参考项目中的 https://github.com/JimmyLv/BibiGPT/blob/main/.example.env 文件

**Comment by Jackiexiao** [comment]
你需要配置 .env 设置环境变量（这个仓库用到很多第三方的服务，sentry supabase 之类），参考项目中的 https://github.com/JimmyLv/BibiGPT/blob/main/.example.env 文件
