### ISSUE TITLE
🚀 功能改善 ：一键复制增加字幕复制按钮

### ISSUE THREAD

**Issue by saccohuo** [JimmyLv/BibiGPT#93]
一键复制增加字幕复制按钮，除了总结之外有时候也需要去看原文细节
![image](https://user-images.githubusercontent.com/13887263/230757259-2c15fde1-874f-466c-97a4-595214108f15.png)

**Comment by JimmyLv** [comment]
感谢反馈！现在各个按钮都能对应各视图所显示的内容啦😁
