### ISSUE TITLE
🚀 功能改善 ：新进入一个已经总结过的页面，加载时间太长

### ISSUE THREAD

**Issue by saccohuo** [JimmyLv/BibiGPT#99]
新进入一个已经总结过的页面，加载时间太长，希望能缩短时间

**Comment by JimmyLv** [comment]
现在已经有总结记录啦！

<img width="1570" alt="BibiGPT 总结记录" src="https://github.com/JimmyLv/BibiGPT/assets/4997466/4f59bc92-1614-46d4-b6f0-ec30fd41ecd6">
